apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:sts::489247846468:assumed-role/voclabs/user3713687=satoshikisaki@hotmail.com
    username: admin
    groups:
        - system:masters
