apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - rolearn: arn:aws:iam::180294201352:root
      username: eks-service-role
      groups:
        - system:masters
