name: Deploy Kubernetes Infra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Kubectl (generic installation method)
      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # # Format check for Terraform files
      # - name: Terraform Format Check
      #   run: terraform fmt -check

      # # Terraform Init
      # - name: Terraform Init
      #   run: terraform init

      # # Terraform Plan
      # - name: Terraform Plan
      #   run: terraform plan

      # # Terraform Apply
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      #     # aws-region: ${{ env.REGION_DEFAULT }}
      #     aws-region: us-east-1

      # - name: Update Kube Config
      #   # run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION_DEFAULT }}            ADICIONAR ENVs
      #   run: aws eks update-kubeconfig --name EKS-fiap-tech-challenge --region us-east-1

      # - name: Deploy EKS Without ALB
      #   run: |
      #     kubectl apply -f eks-without-alb/k8s/eks-deployment.yaml
      #     kubectl apply -f eks-without-alb/k8s/eks-svc.yaml